version: 4.4.{build}

branches:
  only:
    - master

skip_tags: true

image: Visual Studio 2017

install:
  - ps: |
        Install-PackageProvider -Name NuGet -Force
        #Install-Module -Name Pester -Repository PSGallery -Force

test_script:
    - ps: |
        # In case we ever get pester tests in place
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
        }

build:
  project: AutomatedLab.sln

before_build:
  -ps: |
       gci -Filter *.psd1 -Recurse | foreach {(Get-Content $_.FullName -Raw) -replace "ModuleVersion = '\d\.\d\.\d\.\d'", "ModuleVersion = '$env:APPVEYOR_BUILD_VERSION'" | Out-File $_.FullName}
       gci -Filter AssemblyInfo.cs -Recurse | foreach {(Get-Content $_.FullName -Raw) -replace '[assembly: AssemblyVersion("\d\.\d\.\d\.\d")]', "[assembly: AssemblyVersion(`"$env:APPVEYOR_BUILD_VERSION`")]" -replace '[assembly: AssemblyFileVersion("\d\.\d\.\d\.\d")]', "[assembly: AssemblyFileVersion(`"$env:APPVEYOR_BUILD_VERSION`")]" | Out-File $_.FullName}

after_build:
  - ps: |
        # Find MSIs
        $msifiles = Get-ChildItem -Recurse -Filter AutomatedLab.msi
        foreach($f in $msifiles)
        {
          Push-AppVeyorArtifact $f.FullName
        }
        $stagingDirectory = (Resolve-Path ..).Path
        $zipFilePath = Join-Path $stagingDirectory "$(Split-Path $pwd -Leaf).zip"
        Add-Type -assemblyname System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory($pwd, $zipFilePath)

        # Creating NuGet package artifact
        New-Nuspec -packageName $env:APPVEYOR_PROJECT_NAME -version "$($env:APPVEYOR_BUILD_VERSION)" -author "Raimund Andree Per Pedersen Jan-Hendrik Peters" -owners "Jan-Hendrik Peters" -licenseUrl "https://github.com/nyanhp/AutomatedLab/blob/master/LICENSE" -projectUrl "https://github.com/$($env:APPVEYOR_REPO_NAME)" -packageDescription $env:APPVEYOR_PROJECT_NAME -tags "AL" -destinationPath .
        nuget pack ".\$($env:APPVEYOR_PROJECT_NAME).nuspec" -outputdirectory .
        $nuGetPackageName = $env:APPVEYOR_PROJECT_NAME + ".*.nupkg"
        $nuGetPackagePath = (Get-Item $nuGetPackageName).FullName
        Push-AppVeyorArtifact $nuGetPackagePath
artifacts:
  - path: \Installer\bin\Debug\AutomatedLab.msi 
    name: alinstaller
    type: file
deploy:
  release: AutomatedLab-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: YMKyXVrtkuyciwUqQh+UZnCYrL7HgBdIVbTzuLSsVzHQCTF/e5ZLs6lUBPPj53fC # your encrypted token from GitHub
  artifact: alinstaller            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only